### ISSUE TITLE
Can't compile with VS 2019

### ISSUE THREAD

**Issue by jaloji** [Sigil-Ebook/sigil-gumbo#3]
Hi,
Why don't you provide gumbo.dll ?

I use VS 2019 and your vcproject seems to build .lib properly but when I manuelly switch to .DLL it seems to cause multpile linking errors...

I dn't know if its just because I may be a morron but if not can you just make a little more documentation on compiling under Windows in your readme ? 

PS: I juste want to use this with python... and not gumbo itself...

**Comment by kevinhendricks** [comment]
Are you building with cmake?  Exactly what error messages are produced?  Please show a complete build log.

The vcxproj files are 10 years old and not used for any of our internal Sigil builds.

The sigil gumbo dll for Windows is built using cmake and is distributed as part of Sigil.  So a precompiled sigil gumbo dll could probably be extracted from the Sigil Windows installer.

**Comment by kevinhendricks** [comment]
If all you are looking for is something that can be used with python, perhaps this project would be better for you:

https://github.com/kovidgoyal/html5-parser

as it is derived from gumbo and with some changes from sigil-gumbo.

**Comment by dougmassay** [comment]
I think they're trying to use the vs project files in the visualc folder. Something we neither use nor maintain.

**Comment by kevinhendricks** [comment]
That makes sense.  We should probably delete those vcxproj files since they are a google gumbo leftover.

**Comment by dougmassay** [comment]
We use the contents of the include folder in visualc, but the three gumbo.vxproj* files can go.

**Comment by kevinhendricks** [comment]
Understood.  I will make those changes tomorrow when I have access to my dev box.

**Comment by kevinhendricks** [comment]
Removed old vcxproj files.  Updated README.md with generic (from the web) instructions on using cmake and nmake on windows.

Closing this.

**Comment by jaloji** [comment]
Thank you it worked with your new instruction for windows ;)
